version: '2'

services:
  # apigw service
  apigw:
    image: registry.cn-shenzhen.aliyuncs.com/go_micro/apigw:v1.0
    container_name: apigw
    networks:
      - web
    ports:
      - "8081:8081"
    environment:
      - PARAMS=-p 8081 --registry etcd --registry_address etcd1:2379
    labels:
      # traefik固定，与traefik设置的container_name无关
      # apigw 是 container_name
      - "traefik.enable=true" # 必填 否则无法加入traefik
      - "traefik.http.routers.apigw.rule=Host(`apigw.guaosi.com`)" # 外部域名请求
      - "traefik.http.services.apigw.loadbalancer.server.port=8081" # 转发至本容器指定port

  apigw2:
    image: registry.cn-shenzhen.aliyuncs.com/go_micro/apigw:v1.0
    container_name: apigw2
    networks:
      - web
    ports:
      - "8082:8082"
    environment:
      - PARAMS=-p 8082 --registry etcd --registry_address etcd1:2379
    labels:
      # traefik固定，与traefik设置的container_name无关
      # apigw 是 container_name
      - "traefik.enable=true" # 必填 否则无法加入traefik
      - "traefik.http.routers.apigw2.rule=Host(`apigw.guaosi.com`)" # 外部域名请求
      - "traefik.http.services.apigw2.loadbalancer.server.port=8082" # 转发至本容器指定port
networks:
  web:
    external:
      name: gomicro